# Generated by Django 5.0.7 on 2026-05-29 06:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('ingestion_mode', models.CharField(choices=[('csv', 'CSV upload'), ('json', 'JSON upload')], max_length=20)),
                ('source_system', models.CharField(max_length=120)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('received', 'Received'), ('parsed', 'Parsed'), ('partial', 'Partially failed'), ('failed', 'Failed'), ('ready', 'Ready for review'), ('approved', 'Approved')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('source_subtype', models.CharField(blank=True, max_length=40)),
                ('source_system', models.CharField(max_length=120)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('source_document_id', models.CharField(blank=True, max_length=120)),
                ('source_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('source_received_at', models.DateTimeField(auto_now_add=True)),
                ('source_row_number', models.PositiveIntegerField(default=0)),
                ('source_fingerprint', models.CharField(blank=True, max_length=128)),
                ('raw_payload', models.JSONField(default=dict)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('scope_category', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=20)),
                ('activity_category', models.CharField(max_length=80)),
                ('activity_kind', models.CharField(blank=True, max_length=80)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('origin', models.CharField(blank=True, max_length=80)),
                ('destination', models.CharField(blank=True, max_length=80)),
                ('supplier', models.CharField(blank=True, max_length=160)),
                ('vendor', models.CharField(blank=True, max_length=160)),
                ('commodity', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=40)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=12)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('emissions_kg_co2e', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.70'), max_digits=4)),
                ('suspicion_flags', models.JSONField(default=list)),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('warning', 'Warning'), ('failed', 'Failed')], default='warning', max_length=20)),
                ('review_status', models.CharField(choices=[('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='needs_review', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingest.ingestionbatch')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingest.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(choices=[('created', 'Created'), ('imported', 'Imported'), ('edited', 'Edited'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], max_length=20)),
                ('before_state', models.JSONField(default=dict)),
                ('after_state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingest.normalizedrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingest.tenant'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'review_status'], name='ingest_norm_tenant__83c99a_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'source_type'], name='ingest_norm_tenant__e5049c_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'scope_category'], name='ingest_norm_tenant__a8c266_idx'),
        ),
    ]
